export const StationEnum = {
    AIR: "Airport",
    AWE: "AsiaWorld Expo",
    HOK: "Hong Kong",
    KOW: "Kowloon",
    OLY: "Olympic",
    LAK: "Lai King",
    TSY: "Tsing Yi",
    SUN: "Sunny Bay",
    TUC: "Tung Chung",
    WKS: "Wu Kai Sha",
    MOS: "Ma On Shan",
    HEO: "Heng On",
    TSH: "Tai Shui Hang",
    SHM: "Shek Mun",
    CIO: "City One",
    STW: "Sha Tin Wai",
    CKT: "Che Kung Temple",
    HIK: "Hin Keng",
    DIH: "Diamond Hill",
    KAT: "Kai Tak",
    SUW: "Sung Wong Toi",
    TKW: "To Kwa Wan",
    HOM: "Ho Man Tin",
    ETS: "East Tsim Sha Tsui",
    AUS: "Austin",
    NAC: "Nam Cheong",
    MEF: "Mei Foo",
    TWW: "Tsuen Wan West",
    KSR: "Kam Sheung Road",
    YUL: "Yuen Long",
    LOP: "Long Ping",
    TIS: "Tin Shui Wai",
    SIH: "Siu Hong",
    TUM: "Tuen Mun",
    NOP: "North Point",
    QUB: "Quarry Bay",
    YAT: "Yau Tong",
    TIK: "Tiu Keng Leng",
    TKO: "Tseung Kwan O",
    LHP: "LOHAS Park",
    HAH: "Hang Hau",
    POA: "Po Lam",
    ADM: "Admiralty",
    EXC: "Exhibition Centre",
    HUH: "Hung Hom",
    MKK: "Mong Kok East",
    KOT: "Kowloon Tong",
    TAW: "Tai Wai",
    SHT: "Sha Tin",
    FOT: "Fo Tan",
    RAC: "Racecourse",
    UNI: "University",
    TAP: "Tai Po Market",
    TWO: "Tai Wo",
    FAN: "Fanling",
    SHS: "Sheung Shui",
    LOW: "Lo Wu",
    LMC: "Lok Ma Chau",
}